esp_toml_version = 1.0

# This should be a publicly accessible URL of the file server where your firmware binaries are available for download
firmware_images_url = "https://raw.githubusercontent.com/antons-soundskrit/firefly_test/refs/heads/main/"

# Apps that you support and for which the binaries are available to publish. You can have multiple apps as a comma separated list
# The launch pad UI will automatically show these Apps in the available apps dropdown
# There should be a config section per listed App
supported_apps = ["FireflyProcessing", "FireflyRaw"]

# Optional: This should be a publicly accessible URL of the application configuration markdown file
# The markdown file will display the application configuration.
# It might include details such as the revisions of esp-idf, esp-matter, etc. or any other application configuration
config_readme_url = "<APP_CONFIG_README_FILE_URL>"

[FireflyProcessing]
# ESP32 Chipsets for which you have a supported Firmware App. Define a property for each supported chipset in the given format.
chipsets = ["ESP32-S3"]
image.esp32-s3 = "merged-binary_omni_switch.bin"
# Optional: A brief introduction to this app.
description = "Description of the firmware app"

[FireflyRaw]
# ESP32 Chipsets for which you have a supported Firmware App. Define a property for each supported chipset in the given format.
chipsets = ["ESP32-S3"]
image.esp32-s3 = "merged-binary_omni_switch.bin"
# Optional: A brief introduction to this app.
description = "Description of the firmware app"