esp_toml_version = 1.0

# This should be a publicly accessible URL of the file server where your firmware binaries are available for download
firmware_images_url = "https://raw.githubusercontent.com/antons-soundskrit/firefly_test/refs/heads/main/"

# Apps that you support and for which the binaries are available to publish. You can have multiple apps as a comma separated list
# The launch pad UI will automatically show these Apps in the available apps dropdown
# There should be a config section per listed App
supported_apps = ["Firefly-Firmware", "Firefly-Raw"]

[Firefly-Firmware]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "merged-binary_omni_switch.bin"
description = "Latest version of the firefly firmware"

[Firefly-Raw]
chipsets = ["ESP32-S3"]
image.esp32-s3 = "merged-binary_raw.bin"
description = "Development firmware recording the raw singnals from the MEMS mics"